### ISSUE TITLE
Issue w/ Setup & Install Deps

### ISSUE THREAD

**Issue by joshuamcginnis** [syberia/syberia#114]
I'm attempting to setup `syberia` following the instructions in the readme and have encountered a few failures.

The first error was about not having `memoise` installed. I resolved this by installing the package manually `install.packages("memoise")`.

I then restarted R to give it a chance to re-init the deps. It's now stuck at install the `syberia` package:
```R
...
Using tundra 0.3.0.9000 
Installing syberia 0.6.1.9009 from github 
* installing *source* package ‘syberia’ ...
** R
** inst
** preparing package for lazy loading
** help
*** installing help indices
** building package indices
** testing if installed package can be loaded
Installing package into ‘/Users/jmcgin83/.R/lockbox/.staging’
(as ‘lib’ is unspecified)
Error : .onAttach failed in attachNamespace() for 'syberia', details:
  call: contrib.url(repos, type)
  error: trying to use CRAN without setting a mirror
Error: loading failed
Execution halted
ERROR: loading failed
* removing ‘/Users/jmcgin83/.R/lockbox/.staging/syberia’
* installing *source* package ‘syberia’ ...
** R
** inst
** preparing package for lazy loading
** help
*** installing help indices
** building package indices
** testing if installed package can be loaded
Installing package into ‘/Users/jmcgin83/.R/lockbox/.staging’
(as ‘lib’ is unspecified)
Error : .onAttach failed in attachNamespace() for 'syberia', details:
  call: contrib.url(repos, type)
  error: trying to use CRAN without setting a mirror
Error: loading failed
Execution halted
ERROR: loading failed
* removing ‘/Users/jmcgin83/.R/lockbox/.staging/syberia’
Error in install_locked_package(locked_package) : 
  Must have installed the package syberia of version ‘0.6.1.9009’
```

@robertzk @abelcastilloavant Any ideas here?

**Comment by joshuamcginnis** [comment]
FYI, I'm using the readme Robert pointed me to yesterday:
https://github.com/syberia/syberia/blob/0.6-dev/README.md

**Comment by robertzk** [comment]
@joshuamcginnis Try `rm -rf ~/.R/lockbox/syberia` and restarting R. I'll take a look.

**Comment by abelcastilloavant** [comment]
I haven't been able to reproduce locally. Do you get a failure if you install syberia using this?
```
devtools::install_github("syberia/syberia", ref = "0.6.1.9009")
```

**Comment by joshuamcginnis** [comment]
I was able to get `example.sy`up and running with a couple of caveats:

It seems `GITHUB_PAT` env var must be exported (this was not done on my initial attempt):
```
Retrieving dependency info...**.Using github PAT from envvar GITHUB_PAT**
Downloading GitHub repo syberia/syberia@0.6-dev
from URL https://api.github.com/repos/syberia/syberia/zipball/0.6-dev
.Using github PAT from envvar GITHUB_PAT
Downloading GitHub repo robertzk/bettertrace@0.1.1
from URL https://api.github.com/repos/robertzk/bettertrace/zipball/0.1.1
```

Worth noting that `avant-basic`'s CLI requires also requires a Github access token, but it instead relies upon homebrew's `HOMEBREW_GITHUB_API_TOKEN`. Perhaps there's a way to look for this env var first and then request GITHUB_PAT to be set.

Second, once I had the failed attempt, I `rm -Rf ~/.R` and re-attempted the install. Everything worked fine.

However, `base.sy` is now erroring with:
```
Error: Incorrect version of package ‘syberia’ installed. Expected ‘0.6.1.9007’ but downloaded ‘0.6.1.9009’ instead.
```

In ruby, each repo gets its own `gemset` which is just a folder for keeping track of project-specific deps. That would protect from this kind of error. It appears that is not the case for lockbox? How do you address the version mismatch above?

**Comment by abelcastilloavant** [comment]
Regarding the GITHUB_PAT, that seems like a lockbox issue.

Regarding the version mismatch: lockbox does protect against those kind of errors - it uses a `lockfile`, a yaml file that does what you describe for a `gemset`. In this case, there was something wrong with in the lockfile in base.sy. @robertzk addressed it in https://github.com/syberia/base.sy/commit/826a9a238aa0b27e5e8be971f8d5688382d0b230

(I'm guessing the reason we haven't caught it is because we're mostly using the base engine from within other engines, so we don't actually use its lockfile.)

Pull latest master and try again?

**Comment by joshuamcginnis** [comment]
Does lockbox actually allow two separate projects to pull in different versions of the same dep? That appeared to be the issue given the fix was to modify `base.sy` to have the same version of `syberia` as `example.sy`.

**Comment by abelcastilloavant** [comment]
Absolutely yes. In fact, at one time, we had a project that had two different lockfiles (one for `experimental` settings and one for `safe` settings) - users would set an env var that was used to choose which lockfile to use, and they specified different versions for some packages. :)

**Comment by abelcastilloavant** [comment]
In this case I think the lockfile entry for `syberia` was malformed in `base.sy` - the tag reference and the branch reference were mismatched. `example.sy` just happened to have it right.

**Comment by joshuamcginnis** [comment]
I'll go ahead and close this since my original issue has been resolved. Thanks for your help!
