### ISSUE TITLE
404: not found

### ISSUE THREAD

**Issue by guru1982** [syberia/syberia#128]
when I try to install syberia with 

> devtools::install_github("syberia/syberia@install")

this is what i get
```
Downloading GitHub repo syberia/syberia@install
from URL https://api.github.com/repos/syberia/syberia/zipball/install
Installation failed: 404: Not Found
 (404)
```

**Comment by peterhurford** [comment]
Hi. Try just `devtools::install_github("syberia/syberia")` instead from within R or `git clone git@github.com:syberia/example.sy.git && cd example.sy && R` from the command line to see a sample project. I don't think `devtools::install_github("syberia/syberia@install")` is supported anymore. If you see that in the documentation, let us know so we can fix it. Thanks!

**Comment by guru1982** [comment]
thanks for the quick response. Its working. BTW, it has not yet been corrected at http://syberia.io/docs/download.html
where the "syberia@install" version is still mentioned.

**Comment by peterhurford** [comment]
@robertzk ^

**Comment by robertzk** [comment]
Thanks @guru1982! [Fixed](https://github.com/syberia/syberia.github.io/commit/45d279ca445170ba92b3354b29825622a3378223).
