### ISSUE TITLE
file.exists fails on Windows due to use of "~" in file name

### ISSUE THREAD

**Issue by SemanticBeeng** [syberia/syberia#129]
This fails on Windows due to the ~ prefix.

https://github.com/syberia/syberia/blob/312769f94fbd6c0a8eaf10a57a638b2d88c7dd09/R/engine.R#L200

Leads to failure to start Syberia

**Comment by peterhurford** [comment]
Unfortunately, Syberia won't work on Windows for a variety of reasons right now. Windows support is on our long-term roadmap, but unfortunately won't be something we have the capacity to deliver for quite some time. Sorry!

**Comment by SemanticBeeng** [comment]
thanks for quick feedback. this makes it easier for me to make the case for *unix
