### ISSUE TITLE
Better "syberia new"

### ISSUE THREAD

**Issue by robertzk** [syberia/syberia#50]
Really a shortcut for "syberia new application". Then we can have "syberia new server", "syberia new package", "syberia new dashboard" etc for the other project types.

**Comment by kirillseva** [comment]
What's wrong with existing?

**Comment by robertzk** [comment]
Existing is fine, just hide dependency on yo mostly.

**Comment by kirillseva** [comment]
check https://github.com/robertzk/syberia/pull/44
This will install yo and the generator

The only unsolved dep is npm
